name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 检出代码
        uses: actions/checkout@v7

      - name: 安装 pnpm
        uses: pnpm/action-setup@v6
        with:
          version: 10

      - name: 安装 Node
        uses: actions/setup-node@v7
        with:
          node-version: 22
          cache: pnpm

      - name: 安装依赖
        run: pnpm install --frozen-lockfile

      - name: 代码检查
        run: pnpm lint:check

      - name: 类型检查
        run: pnpm type-check

      - name: 构建
        run: pnpm build-only
